/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssistRouteImport } from './routes/assist'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as ProductListRouteRouteImport } from './routes/productList/route'
import { Route as IndexRouteImport } from './routes/index'

const AssistRoute = AssistRouteImport.update({
  id: '/assist',
  path: '/assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductListRouteRoute = ProductListRouteRouteImport.update({
  id: '/productList',
  path: '/productList',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/productList': typeof ProductListRouteRoute
  '/products': typeof ProductsRouteRoute
  '/assist': typeof AssistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/productList': typeof ProductListRouteRoute
  '/products': typeof ProductsRouteRoute
  '/assist': typeof AssistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/productList': typeof ProductListRouteRoute
  '/products': typeof ProductsRouteRoute
  '/assist': typeof AssistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/productList' | '/products' | '/assist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/productList' | '/products' | '/assist'
  id: '__root__' | '/' | '/productList' | '/products' | '/assist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductListRouteRoute: typeof ProductListRouteRoute
  ProductsRouteRoute: typeof ProductsRouteRoute
  AssistRoute: typeof AssistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assist': {
      id: '/assist'
      path: '/assist'
      fullPath: '/assist'
      preLoaderRoute: typeof AssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productList': {
      id: '/productList'
      path: '/productList'
      fullPath: '/productList'
      preLoaderRoute: typeof ProductListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductListRouteRoute: ProductListRouteRoute,
  ProductsRouteRoute: ProductsRouteRoute,
  AssistRoute: AssistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
